### ISSUE TITLE
Missing ; at the end of your JS file

### ISSUE THREAD

**Issue by pallaviOE** [MBehtemam/angular-uuid#2]
This causes very weird error if your JS or .min.js is included in an Angular module.
Uncaught TypeError: object is not a function (anonymous function)
After I manually put in the semicolon at the end of the files, it worked.

**Comment by josejulio** [comment]
PR #5

**Comment by josejulio** [comment]
Resolved by #5 (Merged)

**Comment by MBehtemam** [comment]
thanks.
