### ISSUE TITLE
Bower instruction

### ISSUE THREAD

**Issue by ggarbereder** [MBehtemam/angular-uuid#6]
In the readme it is stated:
bower install angular.uuid2

But correct is:
bower install angular-uuid2

**Comment by tristianradford** [comment]
I correctly installed this with:
**bower install Angular.uuid2**

**Comment by rokoala** [comment]
readme bower install information is wrong. Use **bower install Angular.uuid2**

**Comment by maeishoj** [comment]
with the . i get "bower ENOTFOUND     Package angular.uuid2 not found"
